# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=2

inherit games

DESCRIPTION="various maps for urban terror 4"
HOMEPAGE="http://xmw.de/mirror/urbanterror-maps"

#http://xmw.de/mirror/urbanterror-maps/list
SRC_URI="http://xmw.de/mirror/urbanterror-maps/Heretic.pk3
http://xmw.de/mirror/urbanterror-maps/Or_class.pk3
http://xmw.de/mirror/urbanterror-maps/Or_detention.pk3
http://xmw.de/mirror/urbanterror-maps/TheDayAfter2.pk3
http://xmw.de/mirror/urbanterror-maps/army.pk3
http://xmw.de/mirror/urbanterror-maps/army_IDRC.pk3
http://xmw.de/mirror/urbanterror-maps/bal3void2.pk3
http://xmw.de/mirror/urbanterror-maps/blackbridge.pk3
http://xmw.de/mirror/urbanterror-maps/chronic.pk3
http://xmw.de/mirror/urbanterror-maps/coconutbeta.pk3
http://xmw.de/mirror/urbanterror-maps/estatica.pk3
http://xmw.de/mirror/urbanterror-maps/fortress.pk3
http://xmw.de/mirror/urbanterror-maps/gamershome-fixed.pk3
http://xmw.de/mirror/urbanterror-maps/hell.pk3
http://xmw.de/mirror/urbanterror-maps/history.pk3
http://xmw.de/mirror/urbanterror-maps/interchange.pk3
http://xmw.de/mirror/urbanterror-maps/kellblack.pk3
http://xmw.de/mirror/urbanterror-maps/lostisland_b2.pk3
http://xmw.de/mirror/urbanterror-maps/padgarden-fixed.pk3
http://xmw.de/mirror/urbanterror-maps/padgarden.pk3
http://xmw.de/mirror/urbanterror-maps/padgarden_u1.pk3
http://xmw.de/mirror/urbanterror-maps/padkitchen-fixed.pk3
http://xmw.de/mirror/urbanterror-maps/padkitchen.pk3
http://xmw.de/mirror/urbanterror-maps/padshop-fixed.pk3
http://xmw.de/mirror/urbanterror-maps/papertown.pk3
http://xmw.de/mirror/urbanterror-maps/prison.pk3
http://xmw.de/mirror/urbanterror-maps/q_1upxmas.pk3
http://xmw.de/mirror/urbanterror-maps/q_moonstone.pk3
http://xmw.de/mirror/urbanterror-maps/reqkitchen.pk3
http://xmw.de/mirror/urbanterror-maps/runtfest.pk3
http://xmw.de/mirror/urbanterror-maps/shootingtown.pk3
http://xmw.de/mirror/urbanterror-maps/simpsons_q3.pk3
http://xmw.de/mirror/urbanterror-maps/sirkitbored_b1.pk3
http://xmw.de/mirror/urbanterror-maps/sr8prac.pk3
http://xmw.de/mirror/urbanterror-maps/t3h_0ldSk00l.pk3
http://xmw.de/mirror/urbanterror-maps/t3h_blazin.pk3
http://xmw.de/mirror/urbanterror-maps/t3h_heal.pk3
http://xmw.de/mirror/urbanterror-maps/t3h_healscastle.pk3
http://xmw.de/mirror/urbanterror-maps/t3h_map2010.pk3
http://xmw.de/mirror/urbanterror-maps/t3h_poolparty.pk3
http://xmw.de/mirror/urbanterror-maps/t3hmap.pk3
http://xmw.de/mirror/urbanterror-maps/taumafort_b2.pk3
http://xmw.de/mirror/urbanterror-maps/trainyard-classic.pk3
http://xmw.de/mirror/urbanterror-maps/uptown_snow.pk3
http://xmw.de/mirror/urbanterror-maps/ut42_bohemia.pk3
http://xmw.de/mirror/urbanterror-maps/ut42_ricochet.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_1upfun1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_1upfun1_v2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_Rivalry_b1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_alphabase_b2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_arena1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_arena2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_asylum_b1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_baeza.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bar313.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_barn.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_battlefield_bc.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_battlefront.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bilbo_rough.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_blackhawk.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bliss_a1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_blitzkrieg.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_blizzard.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bluedroid_2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bluestorm_1.4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bogazici_b2t.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bootcamp.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bottle_tdm.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_boxtrot_pro.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_boxtrot_x2b.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_boxtrot_x5.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bridge_rc3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bstjumps_b3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_bstjumps_b4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_burbs_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_burbs_night.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_cambridge_fixed.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_cathedral.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_cemetery666.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_cemetery666_metallica.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_city.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_city2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_city6.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_citygardens.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_cmejumps_torneo1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_coldwar_b1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_coldwar_b2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_commune.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_company_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_concrete.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_crazychristmas.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_curbstompcity.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dam_fixed.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dealey_b2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_deathjumps.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_deception_b6.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_deception_v1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_deception_v2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_desolate_b1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_desolate_rc1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dicks.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_druglord.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_druglord2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dtc.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dust2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dust2_rc.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dust2_v2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dust2_v3b.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dust_a4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dutcherjumps_b1v4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_dville.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_facade_b2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_facade_b4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_ferguson_b12.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_ferguson_b9.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_filtration.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_floyd.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_floydv3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_ftdicks.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_funnyjumps.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_funnyjumps_alpha4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_gloom_b2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_granja.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_guerrilla.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_happyjumptutorial_beta3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_heroic_beta1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_herring.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_hexagon_v1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_honeyride_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_hudson_4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_icyfantasy.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_icyjumps5d.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_icysequel1a.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_icyunleashed_beta5_17.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_imperial_a10.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_intercity_b4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_intermodal_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_iran3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_island_final.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_jerez.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_jumptheshark_beta61.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_jumpthis_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_kingbump.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_kingdom_rc4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_kingdom_rc6.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_kingpin.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_kingpin_rc4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_krazyjumps_beta28.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_laberinto_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_laino_b1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_laneway4_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_littletown4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_loadzone.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_longfall_v3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_malibu_beta4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_maximus_v1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_metro_beta1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_metropolis_b1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_metropolis_b2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_midnight.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_militarybunker_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_mix_v1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_monopoly_beta2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_mooniejumps_b3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_n00b_jailbreak.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_nam.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_nepal.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_nuclear.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_offshore.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_orb3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_orbital.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_orbital_sl.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_pandora_b6.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_pandora_b7.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_paradise.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_paradise_.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_paris_beta_2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_paris_v1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_paris_v2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_pent_b4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_pff.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_pgrounds.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_pgrounds2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_poolday.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_presidio_b24.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_presidio_b28.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_provinggrounds.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_publicworks_beta072.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_quickfight.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_railed.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_rctf1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_rctf2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_rctf4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_reykjavik.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_ricochet.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_ricochet_1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_rip_b4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_rip_b6.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_rivalry_b2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_roma_b23.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_roxeajump_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_rundown.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_sanfrancisco_b1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_science_b3_4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_seasonal.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_sirkitbored_b4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_sirkitbored_b6.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_skeetshoot_2010.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_skyjumps_beta2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_slickjumpsv3_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_slidejumps_a71.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_sliema.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_slumwar.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_sniperhallway.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_spacejumps.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_sparta_v2_1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_splendid.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_streets.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_subterra.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_superman.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_superman_b4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_synchronicity_bio.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_tactics.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_tejen_beta3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_terrorism.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_terrorism3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_terrorism4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_terrorism5.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_terrorism6.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_terrorism7.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_thewall.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_timid_v2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_tohunga_b5.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_tohunga_b8.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_towers.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_train_dl1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_trickmap2_b5.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_twins.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_uberjumps_beta3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_unload_beta.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_valley.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_valley_b2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_valley_r2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_venice_b7.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_vertigo.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_village.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_village_.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_vypla.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_wildwest.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_winterassault_2_b3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_winterassault_2_b4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_winterassault_b3.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_wolf_arena2.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_wootjumps_v4.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_yjumps_a1.pk3
http://xmw.de/mirror/urbanterror-maps/ut4_zement_b1.pk3
http://xmw.de/mirror/urbanterror-maps/ut_Museum.pk3
http://xmw.de/mirror/urbanterror-maps/ut_berch.pk3
http://xmw.de/mirror/urbanterror-maps/ut_canalshores.pk3
http://xmw.de/mirror/urbanterror-maps/ut_complex.pk3
http://xmw.de/mirror/urbanterror-maps/ut_corte_qv.pk3
http://xmw.de/mirror/urbanterror-maps/ut_crate.pk3
http://xmw.de/mirror/urbanterror-maps/ut_demolition.pk3
http://xmw.de/mirror/urbanterror-maps/ut_docks.pk3
http://xmw.de/mirror/urbanterror-maps/ut_encounter.pk3
http://xmw.de/mirror/urbanterror-maps/ut_fahuaran.pk3
http://xmw.de/mirror/urbanterror-maps/ut_forrest.pk3
http://xmw.de/mirror/urbanterror-maps/ut_hamunaptra.pk3
http://xmw.de/mirror/urbanterror-maps/ut_heckenschuetze.pk3
http://xmw.de/mirror/urbanterror-maps/ut_hongkong.pk3
http://xmw.de/mirror/urbanterror-maps/ut_iran.pk3
http://xmw.de/mirror/urbanterror-maps/ut_jihad.pk3
http://xmw.de/mirror/urbanterror-maps/ut_laneway2.pk3
http://xmw.de/mirror/urbanterror-maps/ut_liquid.pk3
http://xmw.de/mirror/urbanterror-maps/ut_littletown2.pk3
http://xmw.de/mirror/urbanterror-maps/ut_lostbase.pk3
http://xmw.de/mirror/urbanterror-maps/ut_oldschool.pk3
http://xmw.de/mirror/urbanterror-maps/ut_once.pk3
http://xmw.de/mirror/urbanterror-maps/ut_pgrounds-nite.pk3
http://xmw.de/mirror/urbanterror-maps/ut_pussyparadise.pk3
http://xmw.de/mirror/urbanterror-maps/ut_rumble.pk3
http://xmw.de/mirror/urbanterror-maps/ut_sled_free.pk3
http://xmw.de/mirror/urbanterror-maps/ut_streets3-daybeta3.pk3
http://xmw.de/mirror/urbanterror-maps/ut_suburb.pk3
http://xmw.de/mirror/urbanterror-maps/ut_the_day_after2.pk3
http://xmw.de/mirror/urbanterror-maps/ut_toxic2.pk3
http://xmw.de/mirror/urbanterror-maps/ut_txantrea_beta2.pk3
http://xmw.de/mirror/urbanterror-maps/ut_uctc.pk3
http://xmw.de/mirror/urbanterror-maps/ut_zero.pk3
http://xmw.de/mirror/urbanterror-maps/vitinground_b5.pk3
http://xmw.de/mirror/urbanterror-maps/wop_backyard.pk3
http://xmw.de/mirror/urbanterror-maps/wop_bath.pk3
http://xmw.de/mirror/urbanterror-maps/wop_cabin.pk3
http://xmw.de/mirror/urbanterror-maps/wop_diner.pk3
http://xmw.de/mirror/urbanterror-maps/wop_padattic.pk3
http://xmw.de/mirror/urbanterror-maps/wop_padkitchen.pk3
http://xmw.de/mirror/urbanterror-maps/wop_padlibrary.pk3
http://xmw.de/mirror/urbanterror-maps/wop_padship.pk3"

LICENSE="as-is"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RESTRICT="mirror"

DEPEND=""
RDEPEND=""

src_unpack() {
	return
}

src_install() {
	insinto /usr/share/games/urbanterror/q3ut4
	local map
	for map in ${A} ; do
		einfo ${map}
		doins "${DISTDIR}"/${map} || die
	done
	prepgamesdirs
}
